### ISSUE TITLE
ubuntu离线版是根本不行的

### ISSUE THREAD

**Issue by tanghw** [Mengkzhaoyun/ansible#1]
https://gitlab.ispacesys.cn/source/cig/raw/master/k8s,访问不了的,百度网盘也就少了好几个文件

**Comment by tanghw** [comment]
pypy,registry-2.6.2.tgz在离线状态下缺少

**Comment by Mengkzhaoyun** [comment]
已修复Baidu Disk缺少的文件：
BAIDU DISK
Link：https://pan.baidu.com/s/1c3J0IZm 
Pass：nbk7

Baidu网盘出现问题用默认的HTTPSERVER做服务也是可以安装的
HTTPSERVER=https://gitlab.ispacesys.cn/source/cig/raw/master/k8s
你在浏览器里看不到目录的，看目录要用下面的地址
https://gitlab.ispacesys.cn/source/cig/tree/master/k8s
