### ISSUE TITLE
coreos 安装到步骤b时出错

### ISSUE THREAD

**Issue by htve** [Mengkzhaoyun/ansible#2]
hi,@mengkzhaoyun

错误如下:

`[root@ansible coreos]# ap b.install.yml

PLAY [coreos] ******************************************************************

TASK [setup] *******************************************************************
ok: [master01]
ok: [worker02]
ok: [worker01]

TASK [wod.coreos-install : template master.yml to /usr/share/oem/coreos-install.yml] ***
skipping: [worker01]
skipping: [worker02]
fatal: [master01]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{ ansible_default_ipv4['address'] }}: 'dict object' has no attribute 'address'"}

TASK [wod.coreos-install : template worker.yml to /usr/share/oem/coreos-install.yml] ***
fatal: [worker01]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{ ansible_default_ipv4['address'] }}: 'dict object' has no attribute 'address'"}
fatal: [worker02]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{ ansible_default_ipv4['address'] }}: 'dict object' has no attribute 'address'"}
	to retry, use: --limit @/etc/ansible/coreos/b.install.retry

PLAY RECAP *********************************************************************
master01                   : ok=1    changed=0    unreachable=0    failed=1   
worker01                   : ok=1    changed=0    unreachable=0    failed=1   
worker02                   : ok=1    changed=0    unreachable=0    failed=1   

`

**Comment by Mengkzhaoyun** [comment]
错误描述看起来是获取不到ipv4，服务器需要配置好静态IP，再执行ansible脚本。

**Comment by htve** [comment]
@Mengkzhaoyun 我已经设置了固定的ip啊,我的步骤是
1.先用
`passwd:
  users:
    - name: root
      password_hash: "$1$maTXmv6V$4UuGlRDpBZtipAhlPZ2/J0"
networkd:
  units:
  - name: 00-static.network
    contents: |
      [Match]
      Name=eno1

      [Network]
      DNS=192.168.0.51
      Address=192.168.3.11/24
      Gateway=192.168.0.1
      DHCP=no
storage:
  files:
  - filesystem: "root"
    path: "/etc/ssh/sshd_config"
    mode: 0600
    contents:
      inline: |
        # Use most defaults for sshd configuration.
        Subsystem sftp internal-sftp
        ClientAliveInterval 180
        UseDNS no
        UsePAM yes
        PermitRootLogin yes
        PrintLastLog no # handled by PAM
        PrintMotd no # handled by PAM`

装好coreos 
2. 用另一个机器,run docker ,然后运行ansible

**Comment by htve** [comment]
我使用的版本是1632.3.0,(1465.7.0也存在同样的问题),请问你使用的CoreOS是哪个版本呢?

**Comment by htve** [comment]
@Mengkzhaoyun 我在官方文档中看到的网络配置中是"name: static.network"而非"name: 00-static.network",不知这有没有关系呢?

**Comment by Mengkzhaoyun** [comment]
我用的是 1576.4.0，你可以检查一下，./coreos/group_vars/systech，注意Network参数，默认是ens32，根据你提供的环境，应修改为eno1。
应该跟上面没有关系，我回头试一下你这个版本的CoreOS...

**Comment by htve** [comment]
@Mengkzhaoyun 
我检查过./coreos/group_vars/systech了,确实是eno1,并且同网段的其它机器能ping通和ssh连接  
我使用1632.3.0 在虚拟机和物理机上有试了一下,同样的错误
![image](https://user-images.githubusercontent.com/12823374/36894555-b2b92836-1e46-11e8-8696-e53f1a33716a.png)
![image](https://user-images.githubusercontent.com/12823374/36894567-c29df696-1e46-11e8-91a2-5b89927f7d33.png)

**Comment by htve** [comment]
@Mengkzhaoyun 我使用1576.4.0在虚拟机上试了一下,同样的问题....有一点点无语啦
![image](https://user-images.githubusercontent.com/12823374/36895142-cbff2afa-1e48-11e8-9218-a1753ef81400.png)

**Comment by Mengkzhaoyun** [comment]
你在CoreOS服务器运行ip a命令我看看结果，是不是有多个IP设置。
对照一下
systech-z01 ~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:e9:e3:56 brd ff:ff:ff:ff:ff:ff
    inet 192.168.74.101/24 brd 192.168.74.255 scope global ens32
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fee9:e356/64 scope link
       valid_lft forever preferred_lft forever

**Comment by htve** [comment]
@mengkzhaoyun
localhost ~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:03:17:10 brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.111/24 brd 192.168.3.255 scope global eth0
       valid_lft forever preferred_lft forever

**Comment by htve** [comment]
我对比了一下 一模一样的，我有点懵了...

发自我的 iPhone

在 2018年3月2日，下午7:21，mengkzhaoyun <notifications@github.com<mailto:notifications@github.com>> 写道：


你在CoreOS服务器运行ip a命令我看看结果，是不是有多个IP设置。
对照一下
systech-z01 ~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: ens32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 00:0c:29:e9:e3:56 brd ff:ff:ff:ff:ff:ff
inet 192.168.74.101/24 brd 192.168.74.255 scope global ens32
valid_lft forever preferred_lft forever
inet6 fe80::20c:29ff:fee9:e356/64 scope link
valid_lft forever preferred_lft forever

**Comment by htve** [comment]
我对比了一下，一模一样的，我有点懵啦！

**Comment by htve** [comment]
@Mengkzhaoyun 我今天又试了一下,全部重新搭建的环境,依然不行.很郁闷啊,请问能否详细指导一下呢?

**Comment by mansoncui** [comment]
我没用这个系统部署过，我之前都是用centos7.3部署的






在 2018-03-05 11:08:40，"Huang Tao" <notifications@github.com> 写道：


@Mengkzhaoyun 我今天又试了一下,全部重新搭建的环境,依然不行.很郁闷啊,请问能否详细指导一下呢?

**Comment by Mengkzhaoyun** [comment]
@htve 
你好，你可以给我发邮件，在邮件中，把你的测试CoreOS服务器给我看看。
mengkzhaoyun@gmail.com

**Comment by htve** [comment]
问题已找到 回头给你pr，是因为子网掩码的问题，模版中写死的24，而我需要21

**Comment by Mengkzhaoyun** [comment]
@htve 
我关闭这个问题了，后面我会更新一下这个网络设置，放到说明里面讲一讲，有需要随时打开再讨论。
