### ISSUE TITLE
flannel有新版本

### ISSUE THREAD

**Issue by htve** [Mengkzhaoyun/ansible#3]
@Mengkzhaoyun flannel已有新的版本v0.10.0,能否升级呢?

**Comment by Mengkzhaoyun** [comment]
可以的，今晚升级脚本，如果你是按我脚本安装的，可以在/etc/kubernetes/downloads下找到flannel的aci，用v0.10.0替换就可以了。
已经将coreos的部署方案中，flannel升级至v0.10.0了，相关的tgz文件，在baidu网盘里面找。
