### ISSUE TITLE
删除node节点的etcd服务

### ISSUE THREAD

**Issue by htve** [Mengkzhaoyun/ansible#4]
hi,@mengkzhaoyun
  我将node节点的etcd3删除,准备只在所有的master节点运行etcd, 导致flanneld服务启动不了,日志如下:  

-- Unit flanneld.service has begun starting up.
Mar 06 18:00:54 worker02 rkt[1477]: rm: unable to resolve UUID from file: open /var/lib/coreos/flannel-wrapper.uuid: no such file or directory
Mar 06 18:00:54 worker02 rkt[1477]: rm: failed to remove one or more pods
Mar 06 18:00:54 worker02 etcdctl[1483]: Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Mar 06 18:00:54 worker02 etcdctl[1483]: ; error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused
Mar 06 18:00:54 worker02 etcdctl[1483]: error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Mar 06 18:00:54 worker02 etcdctl[1483]: error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused
Mar 06 18:00:54 worker02 systemd[1]: flanneld.service: Control process exited, code=exited status=2
Mar 06 18:00:54 worker02 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Mar 06 18:00:54 worker02 systemd[1]: Failed to start flannel - Network fabric for containers (System Application Container).

**Comment by Mengkzhaoyun** [comment]
你检查一下/etc/systemd/system/flanneld.service.d/10-image.conf
根据配置，每个flannel会访问自己节点上的etcd服务，所以如果你想修改etcd集群，这里的配置也需要相应的修改。

**Comment by htve** [comment]
@Mengkzhaoyun  配置如下,
[Unit]
After=network-online.target
[Service]
ExecStartPre=/usr/bin/etcdctl set /spacesystech.com/network2/config '{ "Network": "10.2.0.0/16","Backend": {"Type":"vxlan"} }'

Environment="FLANNELD_IFACE=192.168.2.122"
Environment="FLANNELD_ETCD_ENDPOINTS=http://192.168.2.111:2379"
Environment="FLANNELD_ETCD_PREFIX=/spacesystech.com/network2"
Environment="FLANNEL_IMAGE=/etc/kubernetes/downloads/flannel-v0.10.0.aci"
Environment="RKT_GLOBAL_ARGS=--insecure-options=image"
Environment="FLANNEL_IMAGE_ARGS=--name=flannel"



http://192.168.2.111:2379 就是etcd所在的服务器

**Comment by htve** [comment]
修改  /etc/systemd/system/flanneld.service.d/10-image.conf 中的
ExecStartPre=/usr/bin/etcdctl set /spacesystech.com/network2/config '{ "Network": "10.2.0.0/16","Backend": {"Type":"vxlan"} }'

为
/usr/bin/etcdctl --endpoints=http://192.168.2.111:2379 set /spacesystech.com/network2/config '{ "Network": "10.2.0.0/16","Backend": {"Type":"vxlan"} }'
