### ISSUE TITLE
k8s 1.9.6 已出

### ISSUE THREAD

**Issue by htve** [Mengkzhaoyun/ansible#6]
Hi,@mengkzhaoyun
请更新k8s最新的1.9.6的资源

**Comment by Mengkzhaoyun** [comment]
已经更新了1.9.6相关资源，详见Readme.md

**Comment by htve** [comment]
@Mengkzhaoyun
kubectl 打包有问题哦,请更正
![image](https://user-images.githubusercontent.com/12823374/37822998-1ec29a4e-2ec3-11e8-9f5b-3e64c533a55d.png)

**Comment by Mengkzhaoyun** [comment]
感谢提醒，已经修复这个错误。

2018-03-23 17:53 GMT+08:00 Huang Tao <notifications@github.com>:

**Comment by htve** [comment]
邮件回复时，如果有历史邮件，将会存在链接泄漏，请立即修改你的回复哦
